// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package redisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class AddMultipleGeoPositions extends CustomJavaAction<Boolean>
{
	private String Key;
	private java.util.List<IMendixObject> __GeoPositions;
	private java.util.List<redisconnector.proxies.GeoPosition> GeoPositions;

	public AddMultipleGeoPositions(IContext context, String Key, java.util.List<IMendixObject> GeoPositions)
	{
		super(context);
		this.Key = Key;
		this.__GeoPositions = GeoPositions;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.GeoPositions = new java.util.ArrayList<redisconnector.proxies.GeoPosition>();
		if (__GeoPositions != null)
			for (IMendixObject __GeoPositionsElement : __GeoPositions)
				this.GeoPositions.add(redisconnector.proxies.GeoPosition.initialize(getContext(), __GeoPositionsElement));

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "AddMultipleGeoPositions";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
