// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package redisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import redisconnector.impl.RedisConnector;

/**
 * https://redis.io/commands/zrem
 * 
 * Removes the specified members from the sorted set stored at key. Non existing members are ignored.
 * An error is returned when key exists and does not hold a sorted set.
 * Return value
 * Integer reply, specifically:
 * The number of members removed from the sorted set, not including non existing members.
 */
public class DeleteFromSortedList extends CustomJavaAction<Long>
{
	private String key;
	private String member;

	public DeleteFromSortedList(IContext context, String key, String member)
	{
		super(context);
		this.key = key;
		this.member = member;
	}

	@Override
	public Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		RedisConnector redisconnector = new RedisConnector(); 
		return redisconnector.zrem(key, member);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "DeleteFromSortedList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
