// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package redisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import redisconnector.impl.RedisConnector;

/**
 * https://redis.io/commands/zrem
 */
public class DeleteFromSortedList extends CustomJavaAction<Long>
{
	private String Key;
	private String Member;

	public DeleteFromSortedList(IContext context, String Key, String Member)
	{
		super(context);
		this.Key = Key;
		this.Member = Member;
	}

	@Override
	public Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		RedisConnector redisconnector = new RedisConnector(); 
		return redisconnector.zrem(Key, Member);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "DeleteFromSortedList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
