// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package redisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetGeoPositions extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private String Key;
	private java.util.List<IMendixObject> __Names;
	private java.util.List<redisconnector.proxies.GeoPosition> Names;

	public GetGeoPositions(IContext context, String Key, java.util.List<IMendixObject> Names)
	{
		super(context);
		this.Key = Key;
		this.__Names = Names;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.Names = new java.util.ArrayList<redisconnector.proxies.GeoPosition>();
		if (__Names != null)
			for (IMendixObject __NamesElement : __Names)
				this.Names.add(redisconnector.proxies.GeoPosition.initialize(getContext(), __NamesElement));

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetGeoPositions";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
