// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package redisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import redisconnector.impl.RedisConnector;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns the specified range of elements in the sorted set stored at key. The elements are considered to be ordered from the highest to the lowest score. Descending lexicographical order is used for elements with equal score.
 * Apart from the reversed ordering, ZREVRANGE is similar to ZRANGE.
 * Return value
 * Array reply: list of elements in the specified range (optionally with their scores).
 */
public class GetValuesFromSortedList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private String key;
	private Long start;
	private Long stop;
	private redisconnector.proxies.Enum_Sort sort;

	public GetValuesFromSortedList(IContext context, String key, Long start, Long stop, String sort)
	{
		super(context);
		this.key = key;
		this.start = start;
		this.stop = stop;
		this.sort = sort == null ? null : redisconnector.proxies.Enum_Sort.valueOf(sort);
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		RedisConnector redisconnector = new RedisConnector(); 
		return redisconnector.zrange(this.getContext(), key, start, stop, sort);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetValuesFromSortedList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
