// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package redisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * HGETALL key
 * 
 * Available since 2.0.0.
 * Time complexity: O(N) where N is the size of the hash.
 * Returns all fields and values of the hash stored at key. In the returned value, every field name is followed by its value, so the length of the reply is twice the size of the hash.
 * Return value
 * Array reply: list of fields and their values stored in the hash, or an empty list when key does not exist.
 * Examples
 * redis> HSET myhash field1 "Hello"
 * (integer) 1
 * redis> HSET myhash field2 "World"
 * (integer) 1
 * redis> HGETALL myhash
 * 1) "field1"
 * 2) "Hello"
 * 3) "field2"
 * 4) "World"
 * redis> 
 */
public class HMGETALL extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private String Key;
	private java.util.List<IMendixObject> ListOfObjectsToReturn;

	public HMGETALL(IContext context, String Key, java.util.List<IMendixObject> ListOfObjectsToReturn)
	{
		super(context);
		this.Key = Key;
		this.ListOfObjectsToReturn = ListOfObjectsToReturn;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "HMGETALL";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
