// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package redisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import redisconnector.impl.RedisConnector;

/**
 * Channel can be a pattern with wildcards, see https://redis.io/commands/psubscribe
 * 
 * Posts a message to the given channel.
 * Return value
 * Integer reply: the number of clients that received the message.
 */
public class Publish extends CustomJavaAction<Long>
{
	private String channel;
	private String message;

	public Publish(IContext context, String channel, String message)
	{
		super(context);
		this.channel = channel;
		this.message = message;
	}

	@Override
	public Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		RedisConnector redisconnector = new RedisConnector(); 
		return redisconnector.publish(channel, message);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "Publish";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
