// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package redisconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import redisconnector.impl.RedisConnector;

/**
 * https://redis.io/commands/punsubscribe
 * 
 * Unsubscribes the client from the given patterns, or from all of them if none is given.
 * When no patterns are specified, the client is unsubscribed from all the previously subscribed patterns. In this case, a message for every unsubscribed pattern will be sent to the client.
 */
public class Unsubscribe extends CustomJavaAction<Boolean>
{
	private String Channel;

	public Unsubscribe(IContext context, String Channel)
	{
		super(context);
		this.Channel = Channel;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		RedisConnector redisconnector = new RedisConnector(); 
		redisconnector.unsubscribe(Channel);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "Unsubscribe";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
